version: 0.1

environment_variables:
  plaintext:
    DJANGO_SETTINGS_MODULE: config.settings.test
    SECRET_KEY: nosecret
    DATABASE_DEFAULT_URL: sqlite:///db1.sqlite3
    DATABASE_STREAMDATA_URL: sqlite:///db2.sqlite3
    STREAM_INCOMING_PRIVATE_KEY: changeme
    STREAM_INCOMING_PUBLIC_KEY: changeme
    GOOGLE_API_KEY: changeme
    OPBEAT_ENABLED: False

phases:
  pre_build:
    commands:
      - echo Pulling updates from the git repo
      - git fetch 
      - git pull
  build:
    commands:
      - echo Building the Docker image 
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 816554915038.dkr.ecr.us-east-2.amazonaws.com
      - docker build -t django-website:latest
      - docker tag django-website:latest 816554915038.dkr.ecr.us-east-2.amazonaws.com/django-webiste:latest
      - docker push 816554915038.dkr.ecr.us-east-2.amazonaws.com/django-webiste:latest
  post_build:
    commands:
      - echo Build completed on `date`